import 'package:demoappfortest/models/available_trip_data.dart';
import 'package:demoappfortest/models/bus_data.dart';
import 'package:demoappfortest/models/seat_layout_data_model.dart';

class AppConst {
  static BusData busdata = BusData.fromJson({
    "totalRows": 8,
    "totalColumns": 5,
    "seats": [
      // Lower Deck
      {
        "seatNumber": "L1",
        "row": 0,
        "column": 0,
        "status": "available",
        "fare": 1050,
        "berth": "lower",
        "gender": "any",
        "seatType": "sleeper",
        "isAC": false,
        "tax": 50
      },
      {
        "seatNumber": "L2",
        "row": 0,
        "column": 1,
        "status": "available",
        "fare": 1050,
        "berth": "lower",
        "gender": "female",
        "seatType": "sleeper",
        "isAC": false,
        "tax": 50
      },
      {
        "seatNumber": "L3",
        "row": 0,
        "column": 3,
        "status": "available",
        "fare": 1050,
        "berth": "lower",
        "gender": "any",
        "seatType": "sleeper",
        "isAC": false,
        "tax": 50
      },
      {
        "seatNumber": "L4",
        "row": 0,
        "column": 4,
        "status": "available",
        "fare": 1050,
        "berth": "lower",
        "gender": "male",
        "seatType": "sleeper",
        "isAC": false,
        "tax": 50
      },

      {
        "seatNumber": "L5",
        "row": 1,
        "column": 0,
        "status": "available",
        "fare": 1050,
        "berth": "lower",
        "gender": "any",
        "seatType": "sleeper",
        "isAC": false,
        "tax": 50
      },
      {
        "seatNumber": "L6",
        "row": 1,
        "column": 1,
        "status": "available",
        "fare": 1050,
        "berth": "lower",
        "gender": "female",
        "seatType": "sleeper",
        "isAC": false,
        "tax": 50
      },
      {
        "seatNumber": "L7",
        "row": 1,
        "column": 3,
        "status": "available",
        "fare": 1050,
        "berth": "lower",
        "gender": "any",
        "seatType": "sleeper",
        "isAC": false,
        "tax": 50
      },
      {
        "seatNumber": "L8",
        "row": 1,
        "column": 4,
        "status": "available",
        "fare": 1050,
        "berth": "lower",
        "gender": "any",
        "seatType": "sleeper",
        "isAC": false,
        "tax": 50
      },

      {
        "seatNumber": "L9",
        "row": 2,
        "column": 0,
        "status": "available",
        "fare": 1050,
        "berth": "lower",
        "gender": "male",
        "seatType": "sleeper",
        "isAC": false,
        "tax": 50
      },
      {
        "seatNumber": "L10",
        "row": 2,
        "column": 1,
        "status": "available",
        "fare": 1050,
        "berth": "lower",
        "gender": "female",
        "seatType": "sleeper",
        "isAC": false,
        "tax": 50
      },
      {
        "seatNumber": "L11",
        "row": 2,
        "column": 3,
        "status": "available",
        "fare": 1050,
        "berth": "lower",
        "gender": "male",
        "seatType": "sleeper",
        "isAC": false,
        "tax": 50
      },
      {
        "seatNumber": "L12",
        "row": 2,
        "column": 4,
        "status": "available",
        "fare": 1050,
        "berth": "lower",
        "gender": "any",
        "seatType": "sleeper",
        "isAC": false,
        "tax": 50
      },

      {
        "seatNumber": "L13",
        "row": 3,
        "column": 0,
        "status": "available",
        "fare": 1050,
        "berth": "lower",
        "gender": "any",
        "seatType": "sleeper",
        "isAC": false,
        "tax": 50
      },
      {
        "seatNumber": "L14",
        "row": 3,
        "column": 1,
        "status": "available",
        "fare": 1050,
        "berth": "lower",
        "gender": "female",
        "seatType": "sleeper",
        "isAC": false,
        "tax": 50
      },
      {
        "seatNumber": "L15",
        "row": 3,
        "column": 3,
        "status": "available",
        "fare": 1050,
        "berth": "lower",
        "gender": "any",
        "seatType": "sleeper",
        "isAC": false,
        "tax": 50
      },
      {
        "seatNumber": "L16",
        "row": 3,
        "column": 4,
        "status": "available",
        "fare": 1050,
        "berth": "lower",
        "gender": "any",
        "seatType": "sleeper",
        "isAC": false,
        "tax": 50
      },

      {
        "seatNumber": "L17",
        "row": 4,
        "column": 0,
        "status": "available",
        "fare": 1050,
        "berth": "lower",
        "gender": "male",
        "seatType": "sleeper",
        "isAC": false,
        "tax": 50
      },
      {
        "seatNumber": "L18",
        "row": 4,
        "column": 1,
        "status": "available",
        "fare": 1050,
        "berth": "lower",
        "gender": "any",
        "seatType": "sleeper",
        "isAC": false,
        "tax": 50
      },
      {
        "seatNumber": "L19",
        "row": 4,
        "column": 3,
        "status": "available",
        "fare": 1050,
        "berth": "lower",
        "gender": "any",
        "seatType": "sleeper",
        "isAC": false,
        "tax": 50
      },
      {
        "seatNumber": "L20",
        "row": 4,
        "column": 4,
        "status": "available",
        "fare": 1050,
        "berth": "lower",
        "gender": "female",
        "seatType": "sleeper",
        "isAC": false,
        "tax": 50
      },

      // Upper Deck
      {
        "seatNumber": "U1",
        "row": 0,
        "column": 0,
        "status": "available",
        "fare": 1050,
        "berth": "upper",
        "gender": "any",
        "seatType": "sleeper",
        "isAC": true,
        "tax": 70
      },
      {
        "seatNumber": "U2",
        "row": 0,
        "column": 1,
        "status": "available",
        "fare": 1050,
        "berth": "upper",
        "gender": "female",
        "seatType": "sleeper",
        "isAC": true,
        "tax": 70
      },
      {
        "seatNumber": "U3",
        "row": 0,
        "column": 3,
        "status": "available",
        "fare": 1050,
        "berth": "upper",
        "gender": "any",
        "seatType": "sleeper",
        "isAC": true,
        "tax": 70
      },
      {
        "seatNumber": "U4",
        "row": 0,
        "column": 4,
        "status": "available",
        "fare": 1050,
        "berth": "upper",
        "gender": "male",
        "seatType": "sleeper",
        "isAC": true,
        "tax": 70
      },

      {
        "seatNumber": "U5",
        "row": 1,
        "column": 0,
        "status": "available",
        "fare": 1050,
        "berth": "upper",
        "gender": "any",
        "seatType": "sleeper",
        "isAC": true,
        "tax": 70
      },
      {
        "seatNumber": "U6",
        "row": 1,
        "column": 1,
        "status": "available",
        "fare": 1050,
        "berth": "upper",
        "gender": "female",
        "seatType": "sleeper",
        "isAC": true,
        "tax": 70
      },
      {
        "seatNumber": "U7",
        "row": 1,
        "column": 3,
        "status": "available",
        "fare": 1050,
        "berth": "upper",
        "gender": "any",
        "seatType": "sleeper",
        "isAC": true,
        "tax": 70
      },
      {
        "seatNumber": "U8",
        "row": 1,
        "column": 4,
        "status": "available",
        "fare": 1050,
        "berth": "upper",
        "gender": "any",
        "seatType": "sleeper",
        "isAC": true,
        "tax": 70
      },

      {
        "seatNumber": "U9",
        "row": 2,
        "column": 0,
        "status": "available",
        "fare": 1050,
        "berth": "upper",
        "gender": "female",
        "seatType": "sleeper",
        "isAC": true,
        "tax": 70
      },
      {
        "seatNumber": "U10",
        "row": 2,
        "column": 1,
        "status": "available",
        "fare": 1050,
        "berth": "upper",
        "gender": "any",
        "seatType": "sleeper",
        "isAC": true,
        "tax": 70
      },
      {
        "seatNumber": "U11",
        "row": 2,
        "column": 3,
        "status": "available",
        "fare": 1050,
        "berth": "upper",
        "gender": "any",
        "seatType": "sleeper",
        "isAC": true,
        "tax": 70
      },
      {
        "seatNumber": "U12",
        "row": 2,
        "column": 4,
        "status": "available",
        "fare": 1050,
        "berth": "upper",
        "gender": "male",
        "seatType": "sleeper",
        "isAC": true,
        "tax": 70
      },

      {
        "seatNumber": "U13",
        "row": 3,
        "column": 0,
        "status": "available",
        "fare": 1050,
        "berth": "upper",
        "gender": "any",
        "seatType": "sleeper",
        "isAC": true,
        "tax": 70
      },
      {
        "seatNumber": "U14",
        "row": 3,
        "column": 1,
        "status": "available",
        "fare": 1050,
        "berth": "upper",
        "gender": "female",
        "seatType": "sleeper",
        "isAC": true,
        "tax": 70
      },
      {
        "seatNumber": "U15",
        "row": 3,
        "column": 3,
        "status": "available",
        "fare": int.parse(int.parse(1050.toString()).toString()),
        "berth": "upper",
        "gender": "any",
        "seatType": "sleeper",
        "isAC": true,
        "tax": 70
      },
      {
        "seatNumber": "U16",
        "row": 3,
        "column": 4,
        "status": "available",
        "fare": int.parse(1050.toString()),
        "berth": "upper",
        "gender": "any",
        "seatType": "sleeper",
        "isAC": true,
        "tax": 70
      }
    ]
  });

  static GetAvailableTrips getAvailableTrips = GetAvailableTrips.fromJson({
    "status": {
      "success": true,
      "message": "success",
      "profiledata": {
        "balance": "-23959.4",
        "mode": "POSTPAID",
        "name": "vaagaiapi",
        "allowopsids": ""
      },
      "code": 200
    },
    "availabletrips": [
      {
        "operatorid": "VGT",
        "operatorname": "VAAGAI TRAVELS",
        "routeid": "5904",
        "tripid": "149170",
        "tripid_v2": "365-VT-43",
        "subtripid": "149170",
        "bustype": "A/C Sleeper (2+1) ",
        "totalseats": "30",
        "availseats": "30",
        "ispinksr": "0",
        "isAvailReschedule": false,
        "reschedulePolicy": 0,
        "rescheduleFare": 0,
        "fare": "1000",
        "servicetax": 0,
        "isac": true,
        "seattype": "SLEEPER",
        "convenienceChargePercent": 0,
        "src": "Chennai",
        "srcorder": "0",
        "dst": "Erode",
        "dstorder": "12000",
        "deptime": "2025-08-03 23:50:00",
        "arrtime": "2025-08-04 07:20:00",
        "vehiclenumber": "",
        "amenities":
            "blanket,CCTV camera,emergency exit,GPS tracking,hammer,mobile charger,pillow,reading light,snacks,water bottle,wi-fi",
        "schnote": "COIM SER",
        "isenbldsocialdistancing": "NO",
        "blockingtype": "Dynamic",
        "boardingpoint": {
          "bpDetails": [
            {
              "id": "522635",
              "venue": "Koyembedu Omni Bus Stand",
              "glbid": "286",
              "stnname": "Chennai",
              "address": "Koyembedu Omni Bus stand",
              "contactno": "6666666666",
              "boardtime": "2025-08-03 23:50:00",
              "td": "0",
              "status": "1",
              "stationid": "1",
              "tripid": "5904",
              "sid": "36",
              "timedelay": "11:50 PM"
            },
            {
              "id": "522639",
              "venue": "Muduravoyal",
              "glbid": "518",
              "stnname": "Chennai",
              "address": "Near Erikkarai Bus Stop",
              "contactno": "6666666666",
              "boardtime": "2025-08-04 00:20:00",
              "td": "30",
              "status": "1",
              "stationid": "1",
              "tripid": "5904",
              "sid": "36",
              "timedelay": "12:20 AM (Next Day)"
            },
            {
              "id": "522641",
              "venue": "Porur Toll",
              "glbid": "385",
              "stnname": "Chennai",
              "address": "Near Toll Plaza",
              "contactno": "6666666666",
              "boardtime": "2025-08-04 00:35:00",
              "td": "45",
              "status": "1",
              "stationid": "1",
              "tripid": "5904",
              "sid": "36",
              "timedelay": "12:35 AM (Next Day)"
            },
            {
              "id": "522640",
              "venue": "Perungalathur",
              "glbid": "313",
              "stnname": "Chennai",
              "address": "HOTEL AKASH BAVAN  PERUNGALATHUR",
              "contactno": "6666666666",
              "boardtime": "2025-08-04 01:05:00",
              "td": "75",
              "status": "1",
              "stationid": "1",
              "tripid": "5904",
              "sid": "36",
              "timedelay": "01:05 AM (Next Day)"
            },
            {
              "id": "522645",
              "venue": "Vandaloor",
              "glbid": "314",
              "stnname": "Chennai",
              "address": "Vandaloor Cresent college",
              "contactno": "6666666666",
              "boardtime": "2025-08-04 01:10:00",
              "td": "80",
              "status": "1",
              "stationid": "1",
              "tripid": "5904",
              "sid": "36",
              "timedelay": "01:10 AM (Next Day)"
            },
            {
              "id": "522644",
              "venue": "Urappakkam",
              "glbid": "315",
              "stnname": "Chennai",
              "address": "Near Bus Stop",
              "contactno": "6666666666",
              "boardtime": "2025-08-04 01:15:00",
              "td": "85",
              "status": "1",
              "stationid": "1",
              "tripid": "5904",
              "sid": "36",
              "timedelay": "01:15 AM (Next Day)"
            },
            {
              "id": "522634",
              "venue": "Guduvancheri",
              "glbid": "316",
              "stnname": "Chennai",
              "address": "Guduvancheri Bus Terminus",
              "contactno": "6666666666",
              "boardtime": "2025-08-04 01:20:00",
              "td": "90",
              "status": "1",
              "stationid": "1",
              "tripid": "5904",
              "sid": "36",
              "timedelay": "01:20 AM (Next Day)"
            },
            {
              "id": "522643",
              "venue": "Srm College",
              "glbid": "365",
              "stnname": "Chennai",
              "address": "Near Bus Stop",
              "contactno": "6666666666",
              "boardtime": "2025-08-04 01:25:00",
              "td": "95",
              "status": "1",
              "stationid": "1",
              "tripid": "5904",
              "sid": "36",
              "timedelay": "01:25 AM (Next Day)"
            },
            {
              "id": "522637",
              "venue": "Maraimalainagar",
              "glbid": "317",
              "stnname": "Chennai",
              "address": "Near Bus Stop",
              "contactno": "6666666666",
              "boardtime": "2025-08-04 01:30:00",
              "td": "100",
              "status": "1",
              "stationid": "1",
              "tripid": "5904",
              "sid": "36",
              "timedelay": "01:30 AM (Next Day)"
            },
            {
              "id": "522642",
              "venue": "Singaperumalkoil",
              "glbid": "366",
              "stnname": "Chennai",
              "address": "Near Bus Stop",
              "contactno": "6666666666",
              "boardtime": "2025-08-04 01:35:00",
              "td": "105",
              "status": "1",
              "stationid": "1",
              "tripid": "5904",
              "sid": "36",
              "timedelay": "01:35 AM (Next Day)"
            },
            {
              "id": "522636",
              "venue": "Mahendra City",
              "glbid": "318",
              "stnname": "Chennai",
              "address": "Near Bus Stop",
              "contactno": "6666666666",
              "boardtime": "2025-08-04 01:40:00",
              "td": "110",
              "status": "1",
              "stationid": "1",
              "tripid": "5904",
              "sid": "36",
              "timedelay": "01:40 AM (Next Day)"
            },
            {
              "id": "522633",
              "venue": "Chengalpat Toll",
              "glbid": "319",
              "stnname": "Chennai",
              "address": "Near Toll Plaza",
              "contactno": "6666666666",
              "boardtime": "2025-08-04 01:50:00",
              "td": "120",
              "status": "1",
              "stationid": "1",
              "tripid": "5904",
              "sid": "36",
              "timedelay": "01:50 AM (Next Day)"
            },
            {
              "id": "522638",
              "venue": "Melmaruvathur",
              "glbid": "291",
              "stnname": "Chennai",
              "address": "Near Bus Stop",
              "contactno": "6666666666",
              "boardtime": "2025-08-04 02:20:00",
              "td": "150",
              "status": "1",
              "stationid": "1",
              "tripid": "5904",
              "sid": "36",
              "timedelay": "02:20 AM (Next Day)"
            }
          ]
        },
        "droppingpoint": {
          "dpDetails": [
            {
              "id": "522648",
              "venue": "Bhavani Bypass",
              "address": "Bhavani Bypass",
              "contactno": "6666666666",
              "stationname": "Erode",
              "td": "0",
              "status": "1",
              "stationid": "14",
              "tripid": "5904",
              "sid": "36",
              "glbid": "645",
              "bpoffice": "no",
              "pkupvan": "no",
              "droptime": "2025-08-04 07:20:00",
              "timedelay": "07:20 AM"
            }
          ]
        },
        "cancellationrefrncetime": "2025-08-03 23:50:00",
        "cancellationpolicy": {
          "terms": [
            {
              "hoursbefore": "24:00:00",
              "description": "before 24 hours ",
              "refundpercentage": "90.00",
              "cancellationpercentage": "10.00"
            },
            {
              "hoursbefore": "12:00:00",
              "description": "before 12 hours ",
              "refundpercentage": "75.00",
              "cancellationpercentage": "25.00"
            },
            {
              "hoursbefore": "05:00:00",
              "description": "before 5 hours ",
              "refundpercentage": "50.00",
              "cancellationpercentage": "50.00"
            },
            {
              "hoursbefore": "00:00:00",
              "description": "Within 5 Hours",
              "refundpercentage": "0.00",
              "cancellationpercentage": "100.00"
            }
          ]
        }
      },
      {
        "operatorid": "VGT",
        "operatorname": "VAAGAI TRAVELS",
        "routeid": "5819",
        "tripid": "145050",
        "tripid_v2": "471-VT-36",
        "subtripid": "145050",
        "bustype": "Wave Fly ",
        "totalseats": "34",
        "availseats": "40",
        "ispinksr": "0",
        "isAvailReschedule": false,
        "reschedulePolicy": 0,
        "rescheduleFare": 0,
        "fare": "1799",
        "servicetax": 0,
        "isac": false,
        "seattype": "SEATERSLEEPER",
        "convenienceChargePercent": 0,
        "src": "Chennai",
        "srcorder": "0",
        "dst": "Erode",
        "dstorder": "12000",
        "deptime": "2025-08-03 23:00:00",
        "arrtime": "2025-08-04 08:15:00",
        "vehiclenumber": "",
        "amenities":
            "blanket,CCTV camera,emergency exit,fire-extinguisher,GPS tracking,hammer,mobile charger,mp3 player,pillow,reading light,seat belt,snacks,video,water bottle,wi-fi",
        "schnote": "Chennai to Erode(Via:Kelambakkam)",
        "isenbldsocialdistancing": "NO",
        "blockingtype": "Dynamic",
        "boardingpoint": {
          "bpDetails": [
            {
              "id": "517207",
              "venue": "Koyembedu Omni Bus Stand",
              "glbid": "286",
              "stnname": "Chennai",
              "address": "Koyembedu Omni Bus stand",
              "contactno": "6666666666",
              "boardtime": "2025-08-03 23:00:00",
              "td": "0",
              "status": "1",
              "stationid": "1",
              "tripid": "5819",
              "sid": "1",
              "timedelay": "11:00 PM"
            },
            {
              "id": "517218",
              "venue": "Vadapalani",
              "glbid": "287",
              "stnname": "Chennai",
              "address": "After the Over Bride MTC Bus Stop",
              "contactno": "6666666666",
              "boardtime": "2025-08-03 23:10:00",
              "td": "10",
              "status": "1",
              "stationid": "1",
              "tripid": "5819",
              "sid": "1",
              "timedelay": "11:10 PM"
            },
            {
              "id": "517201",
              "venue": "Ashok Pillar",
              "glbid": "288",
              "stnname": "Chennai",
              "address": "ASHOK PILLAR KFC PICK UP POINT",
              "contactno": "6666666666",
              "boardtime": "2025-08-03 23:15:00",
              "td": "15",
              "status": "1",
              "stationid": "1",
              "tripid": "5819",
              "sid": "1",
              "timedelay": "11:15 PM"
            },
            {
              "id": "517203",
              "venue": "Ekkattuthangal",
              "glbid": "361",
              "stnname": "Chennai",
              "address": "Ambal Nagar Bus Stop",
              "contactno": "6666666666",
              "boardtime": "2025-08-03 23:20:00",
              "td": "20",
              "status": "1",
              "stationid": "1",
              "tripid": "5819",
              "sid": "1",
              "timedelay": "11:20 PM"
            },
            {
              "id": "517210",
              "venue": "Olympia Tech Park Opp",
              "glbid": "362",
              "stnname": "Chennai",
              "address": "Near Bus Stop",
              "contactno": "6666666666",
              "boardtime": "2025-08-03 23:22:00",
              "td": "22",
              "status": "1",
              "stationid": "1",
              "tripid": "5819",
              "sid": "1",
              "timedelay": "11:22 PM"
            },
            {
              "id": "517200",
              "venue": "Alandur Court",
              "glbid": "289",
              "stnname": "Chennai",
              "address": "Near Court",
              "contactno": "6666666666",
              "boardtime": "2025-08-03 23:30:00",
              "td": "30",
              "status": "1",
              "stationid": "1",
              "tripid": "5819",
              "sid": "1",
              "timedelay": "11:30 PM"
            },
            {
              "id": "517219",
              "venue": "Velachery Rs(kaiveli Bus Stop)",
              "glbid": "368",
              "stnname": "Chennai",
              "address": "Kaiveli Bus Stop",
              "contactno": "6666666666",
              "boardtime": "2025-08-03 23:35:00",
              "td": "35",
              "status": "1",
              "stationid": "1",
              "tripid": "5819",
              "sid": "1",
              "timedelay": "11:35 PM"
            },
            {
              "id": "517204",
              "venue": "Kamatchi Hospital",
              "glbid": "369",
              "stnname": "Chennai",
              "address": "Near Bus Stop",
              "contactno": "6666666666",
              "boardtime": "2025-08-03 23:40:00",
              "td": "40",
              "status": "1",
              "stationid": "1",
              "tripid": "5819",
              "sid": "1",
              "timedelay": "11:40 PM"
            },
            {
              "id": "517216",
              "venue": "Thuraipakkam",
              "glbid": "333",
              "stnname": "Chennai",
              "address": "Near Bus Stop",
              "contactno": "6666666666",
              "boardtime": "2025-08-03 23:45:00",
              "td": "45",
              "status": "1",
              "stationid": "1",
              "tripid": "5819",
              "sid": "1",
              "timedelay": "11:45 PM"
            },
            {
              "id": "517217",
              "venue": "Vaagai",
              "glbid": "758",
              "stnname": "Chennai",
              "address": "Address",
              "contactno": "7894561230",
              "boardtime": "2025-08-03 23:45:00",
              "td": "45",
              "status": "1",
              "stationid": "1",
              "tripid": "5819",
              "sid": "1",
              "timedelay": "11:45 PM"
            },
            {
              "id": "517205",
              "venue": "Karapakkam",
              "glbid": "332",
              "stnname": "Chennai",
              "address": "Near Bus Stop",
              "contactno": "6666666666",
              "boardtime": "2025-08-03 23:50:00",
              "td": "50",
              "status": "1",
              "stationid": "1",
              "tripid": "5819",
              "sid": "1",
              "timedelay": "11:50 PM"
            },
            {
              "id": "517213",
              "venue": "Shollinganallur(doller Stop)",
              "glbid": "370",
              "stnname": "Chennai",
              "address": "Near Bus Stop",
              "contactno": "6666666666",
              "boardtime": "2025-08-03 23:53:00",
              "td": "53",
              "status": "1",
              "stationid": "1",
              "tripid": "5819",
              "sid": "1",
              "timedelay": "11:53 PM"
            },
            {
              "id": "517214",
              "venue": "Shollinganallur(signal)",
              "glbid": "371",
              "stnname": "Chennai",
              "address": "Near Bus Stop",
              "contactno": "6666666666",
              "boardtime": "2025-08-03 23:55:00",
              "td": "55",
              "status": "1",
              "stationid": "1",
              "tripid": "5819",
              "sid": "1",
              "timedelay": "11:55 PM"
            },
            {
              "id": "517212",
              "venue": "Sathayabama Univer",
              "glbid": "440",
              "stnname": "Chennai",
              "address": "Near Bus Stop",
              "contactno": "6666666666",
              "boardtime": "2025-08-04 00:00:00",
              "td": "60",
              "status": "1",
              "stationid": "1",
              "tripid": "5819",
              "sid": "1",
              "timedelay": "12:00 AM (Next Day)"
            },
            {
              "id": "517209",
              "venue": "Navalur",
              "glbid": "441",
              "stnname": "Chennai",
              "address": "Near Bus Stop",
              "contactno": "6666666666",
              "boardtime": "2025-08-04 00:10:00",
              "td": "70",
              "status": "1",
              "stationid": "1",
              "tripid": "5819",
              "sid": "1",
              "timedelay": "12:10 AM (Next Day)"
            },
            {
              "id": "517215",
              "venue": "Siruseri",
              "glbid": "442",
              "stnname": "Chennai",
              "address": "SIPCOT Opp Bus Stop",
              "contactno": "6666666666",
              "boardtime": "2025-08-04 00:15:00",
              "td": "75",
              "status": "1",
              "stationid": "1",
              "tripid": "5819",
              "sid": "1",
              "timedelay": "12:15 AM (Next Day)"
            },
            {
              "id": "517211",
              "venue": "Padur",
              "glbid": "443",
              "stnname": "Chennai",
              "address": "Near  Bus Stop",
              "contactno": "6666666666",
              "boardtime": "2025-08-04 00:20:00",
              "td": "80",
              "status": "1",
              "stationid": "1",
              "tripid": "5819",
              "sid": "1",
              "timedelay": "12:20 AM (Next Day)"
            },
            {
              "id": "517206",
              "venue": "Kelambakkam",
              "glbid": "444",
              "stnname": "Chennai",
              "address": "Near Bus Stand",
              "contactno": "6666666666",
              "boardtime": "2025-08-04 00:25:00",
              "td": "85",
              "status": "1",
              "stationid": "1",
              "tripid": "5819",
              "sid": "1",
              "timedelay": "12:25 AM (Next Day)"
            },
            {
              "id": "517202",
              "venue": "Chengalpat",
              "glbid": "290",
              "stnname": "Chennai",
              "address": "Bus Stand to Kalpakkam Piruvu",
              "contactno": "6666666666",
              "boardtime": "2025-08-04 01:20:00",
              "td": "140",
              "status": "1",
              "stationid": "1",
              "tripid": "5819",
              "sid": "1",
              "timedelay": "01:20 AM (Next Day)"
            },
            {
              "id": "517208",
              "venue": "Melmaruvathur",
              "glbid": "291",
              "stnname": "Chennai",
              "address": "Near Bus Stop",
              "contactno": "6666666666",
              "boardtime": "2025-08-04 01:55:00",
              "td": "175",
              "status": "1",
              "stationid": "1",
              "tripid": "5819",
              "sid": "1",
              "timedelay": "01:55 AM (Next Day)"
            }
          ]
        },
        "droppingpoint": {
          "dpDetails": [
            {
              "id": "517227",
              "venue": "Spb Colony",
              "address": "Near Bus Stop",
              "contactno": "6666666666",
              "stationname": "Erode",
              "td": "-10",
              "status": "1",
              "stationid": "14",
              "tripid": "5819",
              "sid": "1",
              "glbid": "353",
              "bpoffice": "no",
              "pkupvan": "no",
              "droptime": "2025-08-04 08:05:00",
              "timedelay": "08:05 AM"
            },
            {
              "id": "517225",
              "venue": "Pallipalayam",
              "address": "Near Bus Stop",
              "contactno": "6666666666",
              "stationname": "Erode",
              "td": "-5",
              "status": "1",
              "stationid": "14",
              "tripid": "5819",
              "sid": "1",
              "glbid": "308",
              "bpoffice": "no",
              "pkupvan": "no",
              "droptime": "2025-08-04 08:10:00",
              "timedelay": "08:10 AM"
            },
            {
              "id": "517223",
              "venue": "Karungalpalayam",
              "address": "Near Bus Stop",
              "contactno": "6666666666",
              "stationname": "Erode",
              "td": "-2",
              "status": "1",
              "stationid": "14",
              "tripid": "5819",
              "sid": "1",
              "glbid": "359",
              "bpoffice": "no",
              "pkupvan": "no",
              "droptime": "2025-08-04 08:13:00",
              "timedelay": "08:13 AM"
            },
            {
              "id": "517222",
              "venue": "Erode Bus Stand",
              "address": "Near PSR Silks",
              "contactno": "6666666666",
              "stationname": "Erode",
              "td": "0",
              "status": "1",
              "stationid": "14",
              "tripid": "5819",
              "sid": "1",
              "glbid": "307",
              "bpoffice": "no",
              "pkupvan": "no",
              "droptime": "2025-08-04 08:15:00",
              "timedelay": "08:15 AM"
            },
            {
              "id": "517224",
              "venue": "Lakshmi Theatre",
              "address": "Near Bus Stop",
              "contactno": "6666666666",
              "stationname": "Erode",
              "td": "5",
              "status": "1",
              "stationid": "14",
              "tripid": "5819",
              "sid": "1",
              "glbid": "346",
              "bpoffice": "no",
              "pkupvan": "no",
              "droptime": "2025-08-04 08:20:00",
              "timedelay": "08:20 AM"
            },
            {
              "id": "517221",
              "venue": "Agraharam",
              "address": "Near Bus Stop",
              "contactno": "6666666666",
              "stationname": "Erode",
              "td": "10",
              "status": "1",
              "stationid": "14",
              "tripid": "5819",
              "sid": "1",
              "glbid": "345",
              "bpoffice": "no",
              "pkupvan": "no",
              "droptime": "2025-08-04 08:25:00",
              "timedelay": "08:25 AM"
            },
            {
              "id": "517226",
              "venue": "Rn Pudhur(amaravathi Nagar)",
              "address": "Near Bus Stop",
              "contactno": "6666666666",
              "stationname": "Erode",
              "td": "15",
              "status": "1",
              "stationid": "14",
              "tripid": "5819",
              "sid": "1",
              "glbid": "344",
              "bpoffice": "no",
              "pkupvan": "no",
              "droptime": "2025-08-04 08:30:00",
              "timedelay": "08:30 AM"
            }
          ]
        },
        "cancellationrefrncetime": "2025-08-03 23:00:00",
        "cancellationpolicy": {
          "terms": [
            {
              "hoursbefore": "24:00:00",
              "description": "before 24 hours ",
              "refundpercentage": "90.00",
              "cancellationpercentage": "10.00"
            },
            {
              "hoursbefore": "12:00:00",
              "description": "before 12 hours ",
              "refundpercentage": "75.00",
              "cancellationpercentage": "25.00"
            },
            {
              "hoursbefore": "05:00:00",
              "description": "before 5 hours ",
              "refundpercentage": "50.00",
              "cancellationpercentage": "50.00"
            },
            {
              "hoursbefore": "00:00:00",
              "description": "Within 5 Hours",
              "refundpercentage": "0.00",
              "cancellationpercentage": "100.00"
            }
          ]
        }
      }
    ]
  });

  static var seatLayoutDataModel = SeatLayoutDataModel.fromJson({
    "status": {
      "success": true,
      "message": "success",
      "profiledata": {
        "balance": "-23959.4",
        "mode": "POSTPAID",
        "name": "vaagaiapi",
        "allowopsids": ""
      },
      "code": 200
    },
    "layout": {
      "maxrows": "4",
      "seattype": "Sleeper",
      "maxcols": "5",
      "decktype": "UpperAndLower",
      "isenbldsocialdistancing": "NO",
      "covidblockedseats": "",
      "blockingtype": "Dynamic",
      "cancellationrefrncetime": "2025-07-31 23:50:00",
      "cancellationpolicy": {
        "terms": [
          {
            "hoursbefore": "24:00:00",
            "description": "before 24 hours ",
            "refundpercentage": "90.00",
            "cancellationpercentage": "10.00"
          },
          {
            "hoursbefore": "12:00:00",
            "description": "before 12 hours ",
            "refundpercentage": "75.00",
            "cancellationpercentage": "25.00"
          },
          {
            "hoursbefore": "05:00:00",
            "description": "before 5 hours ",
            "refundpercentage": "50.00",
            "cancellationpercentage": "50.00"
          },
          {
            "hoursbefore": "00:00:00",
            "description": "Within 5 Hours",
            "refundpercentage": "0.00",
            "cancellationpercentage": "100.00"
          }
        ]
      },
      "seatInfo": [
        {
          "seatNo": "U1",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "1",
          "col": "1",
          "gender": null,
          "seattype": "sleeper",
          "berth": "upper"
        },
        {
          "seatNo": "U3",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "1",
          "col": "2",
          "gender": null,
          "seattype": "sleeper",
          "berth": "upper"
        },
        {
          "seatNo": "U5",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "1",
          "col": "3",
          "gender": null,
          "seattype": "sleeper",
          "berth": "upper"
        },
        {
          "seatNo": "U7",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "1",
          "col": "4",
          "gender": null,
          "seattype": "sleeper",
          "berth": "upper"
        },
        {
          "seatNo": "U9",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "1",
          "col": "5",
          "gender": null,
          "seattype": "sleeper",
          "berth": "upper"
        },
        {
          "seatNo": "U2",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "2",
          "col": "1",
          "gender": null,
          "seattype": "sleeper",
          "berth": "upper"
        },
        {
          "seatNo": "U4",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "2",
          "col": "2",
          "gender": null,
          "seattype": "sleeper",
          "berth": "upper"
        },
        {
          "seatNo": "U6",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "2",
          "col": "3",
          "gender": null,
          "seattype": "sleeper",
          "berth": "upper"
        },
        {
          "seatNo": "U8",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "2",
          "col": "4",
          "gender": null,
          "seattype": "sleeper",
          "berth": "upper"
        },
        {
          "seatNo": "U10",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "2",
          "col": "5",
          "gender": null,
          "seattype": "sleeper",
          "berth": "upper"
        },
        {
          "seatNo": "-",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "3",
          "col": "1",
          "gender": null,
          "seattype": "gangway",
          "berth": "upper"
        },
        {
          "seatNo": "-",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "3",
          "col": "2",
          "gender": null,
          "seattype": "gangway",
          "berth": "upper"
        },
        {
          "seatNo": "-",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "3",
          "col": "3",
          "gender": null,
          "seattype": "gangway",
          "berth": "upper"
        },
        {
          "seatNo": "-",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "3",
          "col": "4",
          "gender": null,
          "seattype": "gangway",
          "berth": "upper"
        },
        {
          "seatNo": "-",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "3",
          "col": "5",
          "gender": null,
          "seattype": "gangway",
          "berth": "upper"
        },
        {
          "seatNo": "U11",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "4",
          "col": "1",
          "gender": null,
          "seattype": "sleeper",
          "berth": "upper"
        },
        {
          "seatNo": "U12",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "4",
          "col": "2",
          "gender": null,
          "seattype": "sleeper",
          "berth": "upper"
        },
        {
          "seatNo": "U13",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "4",
          "col": "3",
          "gender": null,
          "seattype": "sleeper",
          "berth": "upper"
        },
        {
          "seatNo": "U14",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "4",
          "col": "4",
          "gender": null,
          "seattype": "sleeper",
          "berth": "upper"
        },
        {
          "seatNo": "U15",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "4",
          "col": "5",
          "gender": null,
          "seattype": "sleeper",
          "berth": "upper"
        },
        {
          "seatNo": "L1",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "BK",
          "position": "horizontal",
          "row": "1",
          "col": "1",
          "gender": "Female",
          "seattype": "sleeper",
          "berth": "lower"
        },
        {
          "seatNo": "L3",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "1",
          "col": "2",
          "gender": null,
          "seattype": "sleeper",
          "berth": "lower"
        },
        {
          "seatNo": "L5",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "1",
          "col": "3",
          "gender": null,
          "seattype": "sleeper",
          "berth": "lower"
        },
        {
          "seatNo": "L7",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "1",
          "col": "4",
          "gender": null,
          "seattype": "sleeper",
          "berth": "lower"
        },
        {
          "seatNo": "L9",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "1",
          "col": "5",
          "gender": null,
          "seattype": "sleeper",
          "berth": "lower"
        },
        {
          "seatNo": "L2",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "F",
          "position": "horizontal",
          "row": "2",
          "col": "1",
          "gender": null,
          "seattype": "sleeper",
          "berth": "lower"
        },
        {
          "seatNo": "L4",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "2",
          "col": "2",
          "gender": null,
          "seattype": "sleeper",
          "berth": "lower"
        },
        {
          "seatNo": "L6",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "2",
          "col": "3",
          "gender": null,
          "seattype": "sleeper",
          "berth": "lower"
        },
        {
          "seatNo": "L8",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "2",
          "col": "4",
          "gender": null,
          "seattype": "sleeper",
          "berth": "lower"
        },
        {
          "seatNo": "L10",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "2",
          "col": "5",
          "gender": null,
          "seattype": "sleeper",
          "berth": "lower"
        },
        {
          "seatNo": "-",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "3",
          "col": "1",
          "gender": null,
          "seattype": "gangway",
          "berth": "lower"
        },
        {
          "seatNo": "-",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "3",
          "col": "2",
          "gender": null,
          "seattype": "gangway",
          "berth": "lower"
        },
        {
          "seatNo": "-",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "3",
          "col": "3",
          "gender": null,
          "seattype": "gangway",
          "berth": "lower"
        },
        {
          "seatNo": "-",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "3",
          "col": "4",
          "gender": null,
          "seattype": "gangway",
          "berth": "lower"
        },
        {
          "seatNo": "-",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "3",
          "col": "5",
          "gender": null,
          "seattype": "gangway",
          "berth": "lower"
        },
        {
          "seatNo": "L11",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "4",
          "col": "1",
          "gender": null,
          "seattype": "sleeper",
          "berth": "lower"
        },
        {
          "seatNo": "L12",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "4",
          "col": "2",
          "gender": null,
          "seattype": "sleeper",
          "berth": "lower"
        },
        {
          "seatNo": "L13",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "4",
          "col": "3",
          "gender": null,
          "seattype": "sleeper",
          "berth": "lower"
        },
        {
          "seatNo": "L14",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "4",
          "col": "4",
          "gender": null,
          "seattype": "sleeper",
          "berth": "lower"
        },
        {
          "seatNo": "L15",
          "fare": 1000,
          "servicetax": 0,
          "isac": true,
          "stperc": "5",
          "convenienceChargePercent": 0,
          "seatstatus": "A",
          "position": "horizontal",
          "row": "4",
          "col": "5",
          "gender": null,
          "seattype": "sleeper",
          "berth": "lower"
        }
      ]
    }
  });
}
